sudo docker rm $(sudo docker ps -a -q)

sudo docker rmi m0rf30/yap-archlinux
sudo docker rmi m0rf30/yap-amazonlinux-2016.09
sudo docker rmi m0rf30/yap-amazonlinux-2017.03
sudo docker rmi m0rf30/yap-amazonlinux-2017.09
sudo docker rmi m0rf30/yap-amazonlinux-2017.12
sudo docker rmi m0rf30/yap-amazonlinux-1
sudo docker rmi m0rf30/yap-amazonlinux-2
sudo docker rmi m0rf30/yap-centos-6
sudo docker rmi m0rf30/yap-centos-7
sudo docker rmi m0rf30/yap-centos-8
sudo docker rmi m0rf30/yap-debian-jessie
sudo docker rmi m0rf30/yap-debian-stretch
sudo docker rmi m0rf30/yap-debian-wheezy
sudo docker rmi m0rf30/yap-debian-buster
sudo docker rmi m0rf30/yap-fedora-21
sudo docker rmi m0rf30/yap-fedora-22
sudo docker rmi m0rf30/yap-fedora-23
sudo docker rmi m0rf30/yap-fedora-24
sudo docker rmi m0rf30/yap-fedora-25
sudo docker rmi m0rf30/yap-fedora-26
sudo docker rmi m0rf30/yap-fedora-27
sudo docker rmi m0rf30/yap-fedora-28
sudo docker rmi m0rf30/yap-fedora-29
sudo docker rmi m0rf30/yap-fedora-30
sudo docker rmi m0rf30/yap-fedora-31
sudo docker rmi m0rf30/yap-fedora-32
sudo docker rmi m0rf30/yap-genkey
sudo docker rmi m0rf30/yap-opensuse-tumbleweed
sudo docker rmi m0rf30/yap-oraclelinux-7
sudo docker rmi m0rf30/yap-oraclelinux-8
sudo docker rmi m0rf30/yap-ubuntu-precise
sudo docker rmi m0rf30/yap-ubuntu-trusty
sudo docker rmi m0rf30/yap-ubuntu-vivid
sudo docker rmi m0rf30/yap-ubuntu-wily
sudo docker rmi m0rf30/yap-ubuntu-xenial
sudo docker rmi m0rf30/yap-ubuntu-yakkety
sudo docker rmi m0rf30/yap-ubuntu-zesty
sudo docker rmi m0rf30/yap-ubuntu-artful
sudo docker rmi m0rf30/yap-ubuntu-bionic
sudo docker rmi m0rf30/yap-ubuntu-cosmic
sudo docker rmi m0rf30/yap-ubuntu-disco
sudo docker rmi m0rf30/yap-ubuntu-eoan
sudo docker rmi m0rf30/yap-ubuntu-focal
sudo docker rmi m0rf30/yap-ubuntu-groovy
sudo docker rmi base/archlinux
sudo docker rmi archlinux/base
sudo docker rmi amazonlinux:2016.09
sudo docker rmi amazonlinux:2017.03
sudo docker rmi amazonlinux:2017.09
sudo docker rmi amazonlinux:2017.12
sudo docker rmi amazonlinux:1
sudo docker rmi amazonlinux:2
sudo docker rmi centos:6
sudo docker rmi centos:7
sudo docker rmi centos:8
sudo docker rmi debian:jessie
sudo docker rmi debian:stretch
sudo docker rmi debian:wheezy
sudo docker rmi debian:buster
sudo docker rmi fedora:21
sudo docker rmi fedora:22
sudo docker rmi fedora:23
sudo docker rmi fedora:24
sudo docker rmi fedora:25
sudo docker rmi fedora:26
sudo docker rmi fedora:27
sudo docker rmi fedora:28
sudo docker rmi fedora:29
sudo docker rmi fedora:30
sudo docker rmi fedora:31
sudo docker rmi fedora:32
sudo docker rmi opensuse:tumbleweed
sudo docker rmi oraclelinux:7
sudo docker rmi oraclelinux:8
sudo docker rmi ubuntu:precise
sudo docker rmi ubuntu:trusty
sudo docker rmi ubuntu:vivid
sudo docker rmi ubuntu:wily
sudo docker rmi ubuntu:xenial
sudo docker rmi ubuntu:yakkety
sudo docker rmi ubuntu:zesty
sudo docker rmi ubuntu:artful
sudo docker rmi ubuntu:bionic
sudo docker rmi ubuntu:cosmic
sudo docker rmi ubuntu:disco
sudo docker rmi ubuntu:eoan
sudo docker rmi ubuntu:focal
sudo docker rmi ubuntu:groovy

sudo docker rmi $(sudo docker images -q -f dangling=true)
