name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "--enable-all --disable=cyclop,exhaustivestruct,forbidigo,funlen,gochecknoinits,gochecknoglobals,wrapcheck,gofumpt,gocognit,gomnd,gocyclo,maligned,golint,scopelint,interfacer,forcetypeassert"
          # Very strict checks, with deprecated ones disabled
          #golangci_lint_flags: "--enable-all --disable=interfacer,maligned,exhaustivestruct,golint,scopelint,bodyclose,contextcheck,interfacer,nilerr,noctx,rowserrcheck,sqlclosecheck,structcheck,tparallel,unparam,wastedassign"
